#ifndef TIME_TABLE_EVENTS_H_
#define TIME_TABLE_EVENTS_H_

namespace common {

// Grouped events for table.
#define MVINS_TIME_EVENTS_OVERALL \
    ADD_EVENT(FEATURE_DETECTION_EXTRACTION)\
    ADD_EVENT(FEATURE_MATCHING)\
    ADD_EVENT(FEATURE_TRIANGULATION)\
    ADD_EVENT(REMOVE_DYNAMIC_OBJECT)\
    ADD_EVENT(SCAN_MATCHING)\
    ADD_EVENT(HYBIRD_OPTIMIZATION)\
    ADD_EVENT(MARGINALIZATION)\
    ADD_EVENT(POSEGRAPH_OPTIMIZATION)\
    ADD_EVENT(BATCH_OPTIMIZATION)\
    ADD_EVENT(INSERT_LOOP_DATA)\
    ADD_EVENT(SCAN_LOOP_CLOSURE)\
    ADD_EVENT(SCAN_BF_SEARCHING)\
    ADD_EVENT(TUNE_MAP_POSE)\
    ADD_EVENT(SCAN_BATCH_LOOP_CLOSURE)\
    ADD_EVENT(VISUAL_LOOP_CLOSURE)\
    ADD_EVENT(LOOP_MAP_TRACKING)\
    ADD_EVENT(LOOP_GLOBAL_SEARCH)\
    ADD_EVENT(RELOC_INITIALIZATION)\
    ADD_EVENT(VISULIZATION)\
    ADD_EVENT(PROCESS_FRONTEND)\
    ADD_EVENT(PROCESS_BACKEND)\
    ADD_EVENT(FEATURE_TRACKING_TEST)\

#define MVINS_EVENTS \
    MVINS_TIME_EVENTS_OVERALL \

}  // namespace common

#endif  // TIME_TABLE_EVENTS_H_

