load_option: 1
chassis_lidar:
    port: ["/dev/ydlidar"]
    num: 1
    sleep_mode: True
    sleep_delay: 10
    action_name: "ydlidar_ros_action"
    topic_name: "scan"
    frame_id: "laser_frame"
    G7:
        baud_rate: 512000
        ignore_array: ""
        fixed_resolution: True
        reversion: True
        inverted: True
        auto_reconnect: True
        single_chn: False
        intensity: False
        motor_DTR: False
        heart_beat: False
        angle_min: -180
        angle_max: 180
        range_min: 0.1
        range_max: 16.0
        frequency: 10
        sample_rate: 10
        abnormal_ck_cnt: 4
        intensity_bit: 10
    T-mini Pro:
        baud_rate: 230400
        ignore_array: "-152,-132,-122,-95,95,122,132,152"
        fixed_resolution: True
        reversion: True
        inverted: True
        auto_reconnect: True
        single_chn: False
        intensity: True
        motor_DTR: False
        heart_beat: False
        angle_min: -180
        angle_max: 180
        range_min: 0.02
        range_max: 12.0
        frequency: 6
        sample_rate: 4
        abnormal_ck_cnt: 4
        intensity_bit: 8
    TGx:
        baud_rate: 512000
        ignore_array: "-152,-132,-122,-95,95,122,132,152"
        fixed_resolution: True
        reversion: True
        inverted: True
        auto_reconnect: True
        single_chn: False
        intensity: False
        motor_DTR: False
        heart_beat: False
        angle_min: -180
        angle_max: 180
        range_min: 0.05
        range_max: 16.0
        frequency: 10
        sample_rate: 20
        abnormal_ck_cnt: 4
        intensity_bit: 8
chassis_line_lidar:
    port: ["/dev/ttyS4", "/dev/ttyS6"]
    num: 2
    sleep_mode: True
    sleep_delay: 10
    action_name: "ydlidar_line_action"
    topic_name: "ydlidar_line_scan"
    frame_id: "ydlidar_line_frame"
    GS2:
        baud_rate: 921600
        ignore_array: ""
        fixed_resolution: True
        reversion: False
        inverted: True
        auto_reconnect: True
        single_chn: False
        intensity: True
        motor_DTR: False
        heart_beat: False
        angle_min: -180
        angle_max: 180
        range_min: 0.025
        range_max: 0.3
        frequency: 25
        sample_rate: 4
        abnormal_ck_cnt: 4
        intensity_bit: 8
